Objective of this notebook is to create a baseline model with minimal cleaning and feature engineering, of which the results can then be used to compare future models against.

In [63]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import metrics
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [64]:
#Load Dataset
ufc_dataset_df = pd.read_csv('data/ufc-master.csv')

In [65]:
print(ufc_dataset_df.columns)

Index(['R_fighter', 'B_fighter', 'R_odds', 'B_odds', 'R_ev', 'B_ev', 'date',
       'location', 'country', 'Winner',
       ...
       'finish_details', 'finish_round', 'finish_round_time',
       'total_fight_time_secs', 'r_dec_odds', 'b_dec_odds', 'r_sub_odds',
       'b_sub_odds', 'r_ko_odds', 'b_ko_odds'],
      dtype='object', length=119)

In [66]:
#Preview Data
ufc_dataset_df.head()

,R_fighter,B_fighter,R_odds,B_odds,R_ev,B_ev,date,location,country,Winner,...,finish_details,finish_round,finish_round_time,total_fight_time_secs,r_dec_odds,b_dec_odds,r_sub_odds,b_sub_odds,r_ko_odds,b_ko_odds
0,Thiago Santos,Johnny Walker,-150.0,130,66.666667,130.000000,2021-10-02,"Las Vegas, Nevada, USA",USA,Red,...,NaN,5.0,5:00,1500.0,800.0,900.0,2000.0,1600.0,-110.0,175.0
1,Alex Oliveira,Niko Price,170.0,-200,170.000000,50.000000,2021-10-02,"Las Vegas, Nevada, USA",USA,Blue,...,NaN,3.0,5:00,900.0,450.0,350.0,700.0,1100.0,550.0,120.0
2,Misha Cirkunov,Krzysztof Jotko,110.0,-130,110.000000,76.923077,2021-10-02,"Las Vegas, Nevada, USA",USA,Blue,...,NaN,3.0,5:00,900.0,550.0,275.0,275.0,1400.0,600.0,185.0
3,Alexander Hernandez,Mike Breeden,-675.0,475,14.814815,475.000000,2021-10-02,"Las Vegas, Nevada, USA",USA,Red,...,Punch,1.0,1:20,80.0,175.0,900.0,500.0,3500.0,110.0,1100.0
4,Joe Solecki,Jared Gordon,-135.0,115,74.074074,115.000000,2021-10-02,"Las Vegas, Nevada, USA",USA,Blue,...,NaN,3.0,5:00,900.0,165.0,200.0,400.0,1200.0,900.0,600.0

In [67]:
#Select subset of data
#Drop date, location , country, fighter_names for the time being as they hold string data.
#Finish Details anfd total_fight_time_secs not available in dataset for an upcoming event
my_cols = ['R_odds', 'B_odds', 'R_ev', 'B_ev',
       'r_dec_odds', 'b_dec_odds', 'r_sub_odds',
       'b_sub_odds', 'r_ko_odds', 'b_ko_odds', 'Winner']

clean_ufc_df = pd.DataFrame(data= ufc_dataset_df, columns=my_cols)

In [68]:
clean_ufc_df.head()

,R_odds,B_odds,R_ev,B_ev,r_dec_odds,b_dec_odds,r_sub_odds,b_sub_odds,r_ko_odds,b_ko_odds,Winner
0,-150.0,130,66.666667,130.000000,800.0,900.0,2000.0,1600.0,-110.0,175.0,Red
1,170.0,-200,170.000000,50.000000,450.0,350.0,700.0,1100.0,550.0,120.0,Blue
2,110.0,-130,110.000000,76.923077,550.0,275.0,275.0,1400.0,600.0,185.0,Blue
3,-675.0,475,14.814815,475.000000,175.0,900.0,500.0,3500.0,110.0,1100.0,Red
4,-135.0,115,74.074074,115.000000,165.0,200.0,400.0,1200.0,900.0,600.0,Blue

In [69]:
#For 1st pass, just drop rows with nan values
clean_ufc_df = clean_ufc_df.dropna(axis = 'index')

#Overall Statistics
clean_ufc_df.describe()

,R_odds,B_odds,R_ev,B_ev,r_dec_odds,b_dec_odds,r_sub_odds,b_sub_odds,r_ko_odds,b_ko_odds
count,3762.000000,3762.000000,3762.000000,3762.000000,3762.000000,3762.000000,3762.000000,3762.000000,3762.000000,3762.000000
mean,-117.896066,62.564327,94.852194,165.167658,295.190324,414.351143,844.564327,1065.152578,514.664009,647.287347
std,270.693767,248.322922,82.988598,136.654009,232.482449,304.356923,550.153014,627.299893,412.762382,458.944572
min,-1700.000000,-1200.000000,5.882353,8.333333,-440.000000,-200.000000,-370.000000,-1250.000000,-550.000000,-275.000000
25%,-250.000000,-145.000000,40.000000,68.965517,168.000000,220.250000,435.000000,592.750000,240.000000,325.000000
50%,-145.000000,128.000000,68.965517,128.000000,250.000000,345.000000,725.000000,978.500000,435.000000,545.000000
75%,125.000000,210.000000,125.000000,210.000000,400.000000,525.000000,1200.000000,1400.000000,700.000000,885.000000
max,775.000000,1150.000000,775.000000,1150.000000,2200.000000,2600.000000,4665.000000,4785.000000,2675.000000,3200.000000

In [70]:
X = clean_ufc_df.loc[:, clean_ufc_df.columns != 'Winner']
y = clean_ufc_df['Winner']

In [71]:
#Create Training and testing Data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=1)

In [72]:
#Compare and plot different results for the different models
model = RandomForestClassifier(random_state=0)

In [73]:
#Fit Model 
model.fit(X_train, y_train)

RandomForestClassifier(random_state=0)

In [74]:
#Evaluate on test data
y_pred = model.predict(X_test)
#Print results
print(y_pred.shape)
print(y_test.shape)

(941,)
(941,)

In [75]:
#Get Accuracy
accuracy = metrics.accuracy_score(y_test, y_pred)
print(f'test_accuracy:{accuracy}')

#Display Confusion Matrix
cm = metrics.confusion_matrix(y_test, y_pred, labels=model.classes_)
cm_display = metrics.ConfusionMatrixDisplay(confusion_matrix = cm, display_labels=model.classes_)

#Display CM
cm_display.plot()
plt.show()

test_accuracy:0.6068012752391073

Predict Winners for upcoming event

In [82]:
#From the most accurate model, use this data to predict the winner of a more recent card
upcoming_event = pd.read_csv('data/upcoming-event.csv')

upcoming_event.head()

,R_fighter,B_fighter,R_odds,B_odds,R_ev,B_ev,date,location,country,Winner,...,finish_details,finish_round,finish_round_time,total_fight_time_secs,r_dec_odds,b_dec_odds,r_sub_odds,b_sub_odds,r_ko_odds,b_ko_odds
0,Mackenzie Dern,Marina Rodriguez,-195,165,51.282051,165.000000,2021-10-09,"Las Vegas, Nevada, USA",USA,NaN,...,NaN,NaN,NaN,NaN,500,400.0,100,2800.0,900,380.0
1,Randy Brown,Jared Gooden,-265,215,37.735849,215.000000,2021-10-09,"Las Vegas, Nevada, USA",USA,NaN,...,NaN,NaN,NaN,NaN,200,550.0,400,1600.0,215,500.0
2,Tim Elliott,Matheus Nicolau,155,-180,155.000000,55.555556,2021-10-09,"Las Vegas, Nevada, USA",USA,NaN,...,NaN,NaN,NaN,NaN,240,120.0,800,450.0,1600,650.0
3,Sabina Mazo,Mariya Agapova,-190,160,52.631579,160.000000,2021-10-09,"Las Vegas, Nevada, USA",USA,NaN,...,NaN,NaN,NaN,NaN,130,350.0,800,800.0,350,750.0
4,Chris Gutierrez,Felipe Colares,-235,190,42.553191,190.000000,2021-10-09,"Las Vegas, Nevada, USA",USA,NaN,...,NaN,NaN,NaN,NaN,-110,400.0,1000,600.0,400,1200.0

In [80]:

#Create new features
clean_upcoming_event = pd.DataFrame(data=upcoming_event, columns = my_cols)

#Drop Winner 
clean_upcoming_event = clean_upcoming_event.drop(axis= 1, labels=['Winner'])

#Fill na with 0 for now
clean_upcoming_event = clean_upcoming_event.fillna(0)

#Preview
print(clean_upcoming_event)

   R_odds  B_odds        R_ev        B_ev  r_dec_odds  b_dec_odds  r_sub_odds  \
0    -195     165   51.282051  165.000000         500       400.0         100
1    -265     215   37.735849  215.000000         200       550.0         400
2     155    -180  155.000000   55.555556         240       120.0         800
3    -190     160   52.631579  160.000000         130       350.0         800
4    -235     190   42.553191  190.000000        -110       400.0        1000
5    -525     385   19.047619  385.000000         450      1100.0         140
6     165    -195  165.000000   51.282051         300       140.0         650
7    -335     260   29.850746  260.000000        -135         0.0         700
8    -335     260   29.850746  260.000000         400       650.0         800

   b_sub_odds  r_ko_odds  b_ko_odds
0      2800.0        900      380.0
1      1600.0        215      500.0
2       450.0       1600      650.0
3       800.0        350      750.0
4       600.0        400     1200.0
5      2200.0        165      700.0
6       350.0       1100      700.0
7         0.0        400        0.0
8      1400.0       -135      650.0

In [86]:
#Predict Winners 
winners = model.predict(clean_upcoming_event)

#Merge Dataframes
upcoming_event['Predicted Winner'] = winners

#info
predictions = upcoming_event.loc[:, ['R_fighter', 'B_fighter', 'Predicted Winner']]

#Show Outcomes 
print(predictions)

          R_fighter             B_fighter Predicted Winner
0    Mackenzie Dern      Marina Rodriguez             Blue
1       Randy Brown          Jared Gooden              Red
2       Tim Elliott       Matheus Nicolau             Blue
3       Sabina Mazo        Mariya Agapova              Red
4   Chris Gutierrez        Felipe Colares              Red
5  Alexandr Romanov        Jared Vanderaa              Red
6      Charles Rosa         Damon Jackson             Blue
7     Loopy Godinez  Silvana Gomez Juarez              Red
8      Steve Garcia     Charlie Ontiveros              Red